### ISSUE TITLE
Test coverage not showing 100%

### ISSUE THREAD

**Issue by kukkadapukarthik** [JussiSuojanen/friends#4]
test cases are working fine but coverage is not showing 100%

**Comment by JussiSuojanen** [comment]
Hi Karthik,

That actually wasn't even my goal with the tests. I think it is more important to test the core functionality and edge case than to always aim for 100% coverage. For example, if you are working for a client project that has a tight schedule, you always have to balance to what you are using your time to get the most value out of it. 

Many times it is more reasonable to start working with a new feature after you are happy with the tests you wrote for the previous task.

**Comment by kukkadapukarthik** [comment]
ya i am happy but i am unable to test failure case on addfriend and article was nice, easy to understand.
My request is if you had time can you please that test cases to cover code coverage.

**Comment by JussiSuojanen** [comment]
Thanks,

Not sure if I understood everything correct, but the failure test case for adding a friend is handled in the code:

[AddFriendViewModelTests](https://github.com/JussiSuojanen/friends/blob/master/FriendsTests/AddFriendViewModelTests.swift)

Check out the testAddFriendFailure() function in line 35.

**Comment by kukkadapukarthik** [comment]
Is there any idea about dependency injections in swift.  i tried your code in that also test coverage is not showing any percentage.

**Comment by JussiSuojanen** [comment]
Hi Karthik,

I have covered dependency injection in this [blog post](http://swiftyjimmy.com/unit-test-mvvm-in-swift/), but I think this is not related to the original issue that you opened. I'll close this issue since I am not aiming for 100% test coverage. Let's continue the discussion for example on Twitter. Just send me a direct message at @jussisuojanen
