### ISSUE TITLE
PublishSet's OnNext isn't getting called

### ISSUE THREAD

**Issue by bhatti-waqas** [JussiSuojanen/friends#6]
Hi, I used your approach for testing viewModels,
But when I provide mocking apiclient 
onShowError<PublishSet> doesn't getting called for onNext
while it works fine with original api. Don't know what is wrong. Can you please help me ?

**Comment by JussiSuojanen** [comment]
Hi bhatti-waqas,

Do you have the code available somewhere so that I can see it? I think I'll be able to spot if the setup for the test case is missing something. I'd also like to see the mocked network request for the call.

**Comment by devraj1414** [comment]
HI JussiSuojanen,
 I am following you code base, but insteed of using Alamofire for network call I am using NSURLSession.
But its failing the PATCH, request for updating as I am getting an 400 exception in a result.

let param = ["firstname" : "Alizee",
                           "lastname": "Laka",
            "phonenumber": "9876544343"]

        var request = URLRequest(url: url)
        request.httpMethod = "PATCH"
        request.timeoutInterval = 60
        request.httpBody  = try! JSONSerialization.data(withJSONObject: param, options: [])
        URLSession.shared.dataTask(with: request){(data, response, error) in

            guard let statusCode = response?.getStatusCode() else{
                completion(.Failure(.InvalidStatusCode))
                return
            }
            print(statusCode)
            
        }.resume()

//URLResponse Extension
extension URLResponse {
    func getStatusCode() -> Int? {
        if let httpResponse = self as? HTTPURLResponse {
            return httpResponse.statusCode
        }
        return nil
    }
}
